version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: pip
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Chicago"
  - directory: /build-aux
    open-pull-requests-limit: 5
    package-ecosystem: pip
    rebase-strategy: auto
    schedule:
      timezone: "05:00 UTC"
