version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - accels
  - apphub
  - debugpy
  - flathub
  - Flatpak
  - foss
  - gresource
  - Pixbuf
  - Pixelbuf
  - pkgdatadir
  - sourceroot
ignoreWords: []
import: []
