name: deckhub
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    freezed_annotation: ^2.4.4
    json_annotation: ^4.9.0
    dart_mappable: ^4.3.0
    dio: ^5.7.0
    logger: ^2.4.0
    retrofit: ^4.4.1
    hooks_riverpod: ^2.6.1
    flutter_hooks: ^0.20.5
    riverpod_annotation: ^2.6.1
    carousel_slider: ^5.0.0
    dio_cache_interceptor: ^3.5.0
    dio_cache_interceptor_file_store: ^1.2.3
    xdg_directories: ^1.1.0
    handy_window: ^0.4.0
    flutter_widget_from_html_core: ^0.15.2
    url_launcher: ^6.3.1
    glib: ^0.0.1
    odrs: ^0.0.4
    crypto: ^3.0.6
    dbus: ^0.7.10
    auto_route: ^9.2.0
    number_paginator: ^0.4.1
    flux:
        git: https://github.com/bedsteler20/flux.git
    ffi: ^2.1.4
    flutter_pty: ^0.4.2
    xterm: ^4.0.0
    flutter_svg: ^2.1.0
    bson: ^5.0.7
    cached_network_image: ^3.4.1
    slang: ^3.32.0
    slang_flutter: ^3.32.0
    flutter_localizations: # add this
        sdk: flutter
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    build_runner: ^2.4.13
    freezed: ^2.5.7
    json_serializable: ^6.8.0
    dart_mappable_builder: ^4.3.0
    retrofit_generator: ^9.1.3
    riverpod_generator: ^2.6.2
    custom_lint: ^0.7.0
    riverpod_lint: ^2.6.2
    auto_route_generator: ^9.0.0
flutter:
    uses-material-design: true
    fonts:
      - family: Adwaita Sans
        fonts:
          - asset: assets/fonts/AdwaitaSans-Regular.ttf
          - asset: assets/fonts/AdwaitaSans-Italic.ttf
            style: italic