# yaml-language-server: $schema=/home/bedsteler20/Projects/flux/schema.json
variables:
    - &pink "#cba6f7"
    - &text "#cdd6f4"
    - &red "#f38ba8"
    - &base "#1e1e2e"
    - &mantle "#181825"
    - &purple "#cba6f7"
    - &darkText "#1e1e2e"
    - &buttonRadius 8

properties:
    useClientSideDecorations: true

breakpoints:
    xs: 0
    sm: 576
    md: 768
    lg: 992
    xl: 1200
    xxl: 1300

theme:
    useMaterial3: true
    scaffoldBackgroundColor: *base
    colorScheme:
        brightness: dark
        primary: *pink
        onPrimary: *darkText
        error: *red
        onError: *darkText
        surface: *mantle
        onSurface: *text
        secondary: *purple
        onSecondary: *darkText

    appBarTheme:
        backgroundColor: *mantle
        foregroundColor: *text
        elevation: 0


    filledButtonTheme:
        style:
            shape:
                type: rounded
                borderRadius: *buttonRadius

    outlinedButtonTheme:
        style:
            shape:
                type: rounded
                borderRadius: *buttonRadius
