on:
  push:
    tags:
      - "*"
name: Flatpak CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: apphub.flatpak
        manifest-path: build-aux/flatpak/com.bedsteler20.AppHub
        cache-key: flatpak-builder-${{ github.sha }}
