name: Lint

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: streetsidesoftware/cspell-action@v2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: --check --verbose
          src: ./apphub
      - uses: isort/isort-action@master
